FROM registry.redhat.io/ubi8/ubi

# ---------------------------------------------------
# TESTED by Valentin Dirken - 04/11/2021
# PHP Version 7.2 - 7.3 - 7.4 
# PORT = 8080 - 8443
# + email SMTP (plugin: msmtp)
# ---------------------------------------------------
# ORACLE is not installed
# mysql_connect is not supported --> mysqli or PDO_MYSQL (installed)
# You can copy-paste this Dockerfile.
# ---------------------------------------------------

ENV PHP_VERSION=7.4 # 7.2 - 7.3 - 7.4 
ENV EMAIL_NO_REPLY_SMTP=xxxxxxx@domain.be
ENV SMTP_HOST=smtp.domain.be


RUN yum --disableplugin=subscription-manager -y module enable php:$PHP_VERSION \
  && yum --disableplugin=subscription-manager -y install httpd php \
  && yum --disableplugin=subscription-manager clean all

# All files in public_html directory are moved to /var/www/html
COPY public_html/ /var/www/html/

# Openshift wants a port above 1000. Leave it at 8080
RUN sed -i 's/Listen 80/Listen 8080/' /etc/httpd/conf/httpd.conf \
  && mkdir /run/php-fpm \
  && chgrp -R 0 /var/log/httpd /var/run/httpd /run/php-fpm \
  && chmod -R g=u /var/log/httpd /var/run/httpd /run/php-fpm

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
RUN dnf clean all && rm -r /var/cache/dnf  && dnf upgrade -y && dnf update -y 
RUN dnf install -y yum-utils
RUN dnf module -y reset php
RUN dnf module -y install php:remi-$PHP_VERSION
RUN dnf update
RUN yum install -y gd msmtp && yum clean all -y

# Command to install additional packages:
RUN dnf install -y --nobest --skip-broken php  php-cli php-fpm php-mysqlnd php-zip php-devel php-gd php-mcrypt php-mbstring php-curl php-xml php-pear php-bcmath php-json

#RUN yum list php*

# Config email
RUN echo "account default" >> /etc/msmtprc
RUN echo "host ${SMTP_HOST}" >> /etc/msmtprc
RUN echo "logfile /var/log/msmtp.log" >> /etc/msmtprc
RUN echo "from ${EMAIL_NO_REPLY_SMTP}" >> /etc/msmtprc
RUN touch /var/log/msmtp.log
RUN sed -i 's/sendmail_path = \/usr\/sbin\/sendmail -t -i/sendmail_path = \/usr\/bin\/msmtp -t/' /etc/php.ini
RUN touch /var/log/msmtp.log && \
     chown apache:0 /var/log/msmtp.log && \
     chmod g+rwX /var/log/msmtp.log
# php -r "mail('username@domain.be','Test Mail PHP', 'This is a test mail from PHP');"

RUN php --modules
RUN php --version

WORKDIR /var/www/html/

EXPOSE 8080 # HTTP
EXPOSE 8443 # HTTPS

USER 1001

CMD php-fpm & httpd -D FOREGROUND
