# Valentin Dirken - UBI8 - Openshift - PHP 7.4 + mail() 
FROM registry.redhat.io/ubi8/ubi

RUN yum --disableplugin=subscription-manager -y module enable php:7.4 \
  && yum --disableplugin=subscription-manager -y install httpd php \
  && yum --disableplugin=subscription-manager clean all

ADD index.php /var/www/html

RUN sed -i 's/Listen 80/Listen 8080/' /etc/httpd/conf/httpd.conf \
  && mkdir /run/php-fpm \
  && chgrp -R 0 /var/log/httpd /var/run/httpd /run/php-fpm \
  && chmod -R g=u /var/log/httpd /var/run/httpd /run/php-fpm

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN yum install -y gd msmtp && yum clean all -y

RUN echo "account default" >> /etc/msmtprc
RUN echo "host smtp.domain.be" >> /etc/msmtprc
RUN echo "logfile /var/log/msmtp.log" >> /etc/msmtprc
RUN echo "from no-reply@domain.be" >> /etc/msmtprc
RUN touch /var/log/msmtp.log

RUN sed -i 's/sendmail_path = \/usr\/sbin\/sendmail -t -i/sendmail_path = \/usr\/bin\/msmtp -t/' /etc/php.ini

RUN touch /var/log/msmtp.log && \
     chown apache:0 /var/log/msmtp.log && \
     chmod g+rwX /var/log/msmtp.log
     
# php -r "mail('youremail@domain.be','Test Mail PHP', 'This is a test mail from PHP');"
  
EXPOSE 8080

USER 1001

CMD php-fpm & httpd -D FOREGROUND
